/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aafinalassignment;

import org.junit.Test;

import aafinalassignment.part_1.OtherArray;

import static org.junit.Assert.*;

public class OtherArrayTest {

    ///////////////////////////////////////////////////////////////
    ///                     Constructor tests                   ///
    ///////////////////////////////////////////////////////////////

    @Test
    /**
     * Test construction of OtherArray with the alpha arg as the minimum possible
     * integer.
     */
    public void ConstructionTest01() {
        assertThrows(IllegalArgumentException.class, () -> {
            OtherArray x = new OtherArray(new int[] { 1, 2, 3, 4, 5, 6, 7, 8, 9 }, Integer.MIN_VALUE);
        });
    }

    @Test
    /**
     * Test construction of OtherArray with the alpha arg as maximum possible
     * integer.
     */
    public void ConstructionTest02() {
        assertThrows(IllegalArgumentException.class, () -> {
            OtherArray x = new OtherArray(new int[] { 1, 2, 3, 4, 5, 6, 7, 8, 9 }, Integer.MAX_VALUE);
        });

    }

    @Test
    /**
     * Test construction of OtherArray with the alpha arg as 0.
     */
    public void ConstructionTest03() {
        OtherArray x = new OtherArray(new int[] { 1, 2, 3, 4, 5, 6, 7, 8, 9 }, 0);
    }

    @Test
    /**
     * Test construction of OtherArray with the alpha arg as 0.5.
     */
    public void ConstructionTest04() {
        OtherArray x = new OtherArray(new int[] { 1, 2, 3, 4, 5, 6, 7, 8, 9 }, 0.5);
    }

    @Test
    /**
     * Test construction of OtherArray with the alpha arg as 1.
     */
    public void ConstructionTest05() {
        OtherArray x = new OtherArray(new int[] { 1, 2, 3, 4, 5, 6, 7, 8, 9 }, 1);
    }

    ///////////////////////////////////////////////////////////////
    ///                     Pred        tests                   ///
    ///////////////////////////////////////////////////////////////

    @Test
    /**
     * Test pred function with empty array.
     */
    public void PredTestWithNoElements() {
        assertThrows(IllegalArgumentException.class, () -> {
            OtherArray x = new OtherArray(new int[] {}, 0.5);
        });
    }
    
    @Test
    /**
     * Test pred function with an array containing negative and
     * positive integers.
     */
    public void PredTestWithNegativeIntegers() {
        OtherArray x = new OtherArray(new int[] { -10, -5, 0, 5, 10 }, 0.5);
        assertEquals(0, x.pred(1));
    }

    @Test
    /**
     * Test pred function with an array containing one element.
     */
    public void PredTestWithOneElement() {
        OtherArray x = new OtherArray(new int[] { 1 }, 0.5);
        assertEquals(1, x.pred(5));
    }

    @Test
    /**
     * Test pred function with the target value out of the range of
     * original array.
     */
    public void PredTestXOutOfRange() {
        OtherArray x = new OtherArray(new int[] { 1, 2, 3, 4, 5, 6, 7, 8, 9 }, 0.5);
        assertEquals(9, x.pred(20)); // 20 not in array.
    }

    @Test
    /**
     * Test pred function with an array containing duplicate values.
     */
    public void PredTestWithDuplicateValues() {
        OtherArray x = new OtherArray(new int[] { 1, 1, 2, 2, 3, 3, 4, 4, 5, 5 }, 0.5);
        assertEquals(3, x.pred(3));
    }

    @Test
    /**
     * Test pred function with alpha arg at the boundaries.
     */
    public void PredTestAlphaAtBoundary() {
        OtherArray x = new OtherArray(new int[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 }, 1);
        assertEquals(5, x.pred(5));

        x = new OtherArray(new int[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 }, 0);
        assertEquals(5, x.pred(5));
    }

    @Test
    /**
     * Test pred function with varying sizes of arrays (1-101) and alpha set
     * to 0.5.
     */
    public void PredTestVaryingArraysAlpha05() {
        for (int i = 1; i <= 101; i++) {
            int[] arr = new int[i];
            for (int j = 0; j < i; j++) {
                arr[j] = j + 1;
            }

            OtherArray x = new OtherArray(arr, 0.5);

            if (i == 0) { // when array is empty, we return the min int value
                assertEquals(Integer.MIN_VALUE, x.pred(5));
            } else if (i >= 5) { // when array is larger or equal to 5, we expect the result of pred to be 5
                assertEquals(5, x.pred(5));
            } else { // when array has less than 5 elements, we expect the result of pred to be the largest element in the array
                assertEquals(i, x.pred(5));
            }
        }
    }

    @Test
    /**
     * Test pred function with varying sizes of arrays (1-101) and alpha set
     * to 0.
     */
    public void PredTestVaryingArraysAlpha00() {
        for (int i = 1; i <= 101; i++) {
            int[] arr = new int[i];
            for (int j = 0; j < i; j++) {
                arr[j] = j + 1;
            }

            OtherArray x = new OtherArray(arr, 0.0);

            if (i == 0) { // when array is empty, we return the min int value
                assertEquals(Integer.MIN_VALUE, x.pred(5));
            } else if (i >= 5) { // when array is larger or equal to 5, we expect the result of pred to be 5
                assertEquals(5, x.pred(5));
            } else { // when array has less than 5 elements, we expect the result of pred to be the largest element in the array
                assertEquals(i, x.pred(5));
            }
        }
    }

    @Test
    /**
     * Test pred function with varying sizes of arrays (1-101) and alpha set
     * to 1.0.
     */
    public void PredTestVaryingArraysAlpha10() {
        for (int i = 1; i <= 101; i++) {
            int[] arr = new int[i];
            for (int j = 0; j < i; j++) {
                arr[j] = j + 1;
            }

            OtherArray x = new OtherArray(arr, 1.0);

            if (i == 0) { // when array is empty, we return the min int value
                assertEquals(Integer.MIN_VALUE, x.pred(5));
            } else if (i >= 5) { // when array is larger or equal to 5, we expect the result of pred to be 5
                assertEquals(5, x.pred(5));
            } else { // when array has less than 5 elements, we expect the result of pred to be the largest element in the array
                assertEquals(i, x.pred(5));
            }
        }
    }

    ///////////////////////////////////////////////////////////////
    ///                     Block       tests                   ///
    ///////////////////////////////////////////////////////////////

    @Test
    public void BlockTest01() {
        OtherArray x = new OtherArray(new int[]{1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18}, 0.5);
        int[] numbers = {
            7, 9, 4, 16, 14, 
            10, 28, 4, 13, 49, 
            16, 37, 52, 6, 43, 
            22, 11, 19, -1, 12, 
            25, -1, 10, -1, -1, 
            13, -1, 31, 2, 34, 
            -1, 1, -1, -1, 3, 
            -1, -1, 17, 40, -1, 
            18, -1, -1, 7, 46,
            -1, 8, -1, -1, 15,
            -1, -1, 5, -1
        }; // Checked on paper
        assertArrayEquals(numbers, x.getOtherArray());        
    }
}